name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Якщо у тебе `master`, заміни на `master`

jobs:
  build_and_deploy:
    name: Build and Deploy Flutter Web
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_UAWERSOMETEST }}"
          channelId: live
