name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Якщо у тебе `master`, заміни на `master`

jobs:
  build_and_deploy:
    name: Build and Deploy Flutter Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Flutter manually
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip xz-utils
          curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.29.0-stable.tar.xz
          tar xf flutter_linux_3.29.0-stable.tar.xz
          echo "export PATH=`pwd`/flutter/bin:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          flutter/bin/flutter --version

      - name: Install dependencies
        run: |
          flutter/bin/flutter pub get

      - name: Build Flutter Web
        run: |
          flutter/bin/flutter build web

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_UAWERSOMETEST }}"
          channelId: live
